export const ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TODO_NOT_FOUND: 'TODO_NOT_FOUND',
  MEMO_NOT_FOUND: 'MEMO_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND_FOR_OAUTH: 'USER_NOT_FOUND_FOR_OAUTH',
} as const;
